### ISSUE TITLE
modules/lsp-common-lib: No such file or directory.

### ISSUE THREAD

**Issue by yurivict** [sadko4u/timbre-mill#3]
Are these supposed to be added as git modules?

**Comment by sadko4u** [comment]
Hello!
You can use source code tarballs attached to the release: https://github.com/sadko4u/timbre-mill/releases/download/0.5.6/timbre-mill-src-0.5.6.tar.gz
They contain all desired stuff for building.

By the other side, you can fetch all missing modules by:
```
make config
make fetch
```

**Comment by yurivict** [comment]
FYI: This tartall has the top directory timbre-mill when it should be timbre-mill-0.5.6. Most projects add version to that directory, and some tools depend on this.

**Comment by yurivict** [comment]
> You can use source code tarballs attached to the release [...]

Yes. But it's better to also have git modules because some people would like to build intermediate revisions for various reasons and these can't be easily built w/out git modules.

**Comment by sadko4u** [comment]
I'm not using git modules because each of the submodules should also use the git modules of the same set and the recursive checkout will fail.
